export const SET_PROFILE = 'SET_PROFILE';
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const SET_COLLECTED_PLAYLISTS = 'SET_COLLECTED_PLAYLISTS';
export const SET_CREATED_PLAYLISTS = 'SET_CREATED_PLAYLISTS';
